name: caching and artifacts

on: [workflow_dispatch]

jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: "npm-cache"
      - name: Display cache output
        run: |
          echo "Cache key: ${{ steps.cache-node-modules.outputs.cache-key }}"
          echo "Cache hit: ${{ steps.cache-node-modules.outputs.cache-hit }}"
          echo "${{ toJson(steps.cache-node-modules.outputs) }}"


      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
            console.log(res.data)