name: Concurrency 1
run-name: Concurrency 1 (${{ inputs.environment }})
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: string # Fixed invalid type
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
  cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        run: echo '${{ toJson(github) }}'
      - name: Print env context
        run: echo '${{ toJson(env) }}'
      - name: Print job context
        run: echo '${{ toJson(job) }}'
      - name: Print runner context
        run: echo '${{ toJson(runner) }}'
      - name: Print steps context
        run: echo '${{ toJson(steps) }}'
      - name: Print strategy context
        run: echo '${{ toJson(strategy) }}'
      - name: Print inputs context
        run: echo '${{ toJson(inputs) }}'
      - name: Print matrix context
        run: echo '${{ toJson(matrix) }}'
      - run: sleep 30