name: Quoting Test Workflow

on:
  workflow_dispatch:

jobs:
  quoting-test:
    runs-on: ubuntu-latest
    steps:
      - name: No quotes
        run: echo ${{ github.actor }}

      - name: Double quotes
        run: echo "${{ github.actor }}"

      - name: Single quotes
        run: echo '${{ github.actor }}'

      - name: toJson with single quotes
        run: echo '${{ toJson(github) }}'

      - name: Broken expression (will fail but continue)
        run: echo '${{ github.actor}}'
        continue-on-error: true

      - name: Bash variable with single quotes
        run: |
          MYVAR=hello
          echo '$MYVAR'

      - name: Bash variable with double quotes
        run: |
          MYVAR=hello
          echo "$MYVAR"
