name: Workflow Commands
on:
  push:
    branches: [master]
jobs:
  workflow-command-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setting an error message
        id: set-error
        run: |
          echo "::error::This is a custom error message"
      
      - name: Setting an error message with parameters
        id: set-error-params
        run: |
          echo "::error title=Error title, file=app.js,line=2, endLine=3,col=7::This is a custom error message"
      
      - name: Setting an notice message with parameters
        id: set-notice-params
        run: |
          echo "::notice title = notice title, file=app.js,line=2, endLine=3,col=7::This is a custom notice message"
      
      - name: Setting an Warning message with parameters
        id: set-Warning-params
        run: |
          echo "::warning title = Warning title, file=app.js,line=2, endLine=3,col=7::This is a custom Warning message"
      